# Tomcat
server:
  port: 8989

spring:
  profiles:
    active: dev
  #这里加了，启动类上就不用加这个排除
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbs:
       db1:
         driverClassName: org.postgresql.Driver
         url: jdbc:postgresql://localhost:5432/db_test1?useUnicode=true&characterEncoding=utf8
         username: postgres
         password: root
       db2:
         driverClassName: org.postgresql.Driver
         url: jdbc:postgresql://localhost:5432/db_test2
         username: postgres
         password: root

mybatis:
  configuration:
    # \u8FD4\u56DE\u4E3B\u952E
    use-generated-keys: true
    # \u5F00\u542F\u9A7C\u5CF0\u529F\u80FD
    map-underscore-to-camel-case: true
  #mapper.xml\u4E2D\u5F15\u7528\u5230\u7684\u7684\u5B9E\u4F53\u7C7B\u4E0D\u5199\u5168\u7C7B\u540D\uFF0C\u53EA\u5199\u4E00\u4E2A\u5B9E\u4F53\u7C7B\u540D\u65F6\uFF0C\u4F1A\u7528\u5230\u4E0B\u9762\u8FD9\u4E2A\u914D\u7F6E
  type-aliases-package: com.lzy.pojo
  # mapper\u7684\u4F4D\u7F6E
  mapper-locations: classpath*:com/lzy/**/*.xml