# Tomcat
server:
  port: 8989

spring:
  profiles:
    active: dev #\u5F00\u53D1\u73AF\u5883
  ############################# \u591A\u6570\u636E\u6E90\u914D\u7F6E##############################
  ## \u53BB\u9664druid\u914D\u7F6E\u3002\u662F\u5426\u9700\u8981\uFF0C\u6839\u636Edruid\u8FDE\u63A5\u6C60\u7684\u7C7B\u578B\u3002\u5982\u679Cdruid\u8FDE\u63A5\u6C60\u4E3Astarter\u7C7B\u578B\uFF0C\u5219\u9700\u8981\u6392\u9664\u3002\u5426\u5219\uFF0C\u4E0D\u9700\u8981\u3002
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db1:
        #url: jdbc:postgresql://localhost:5432/db_test1
        #driver-class-name: org.postgresql.Driver
        #p6spy SQL\u6027\u80FD\u5206\u6790\u63D2\u4EF6
        driverClassName: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:postgresql://localhost:5432/db_test1?useUnicode=true&characterEncoding=utf8
        username: postgres
        password: root
        initial-size: 5   # \u8FDE\u63A5\u6C60\u521D\u59CB\u5316\u8FDE\u63A5\u6570\u91CF
        min-idle: 5      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u6570
        max-active: 20    # \u8FDE\u63A5\u6C60\u6700\u5927\u6D3B\u8DC3\u8FDE\u63A5\u6570
        pool-prepared-statements: true #\u662F\u5426\u7F13\u5B58preparedStatement,mysql5.5+\u5EFA\u8BAE\u5F00\u542F
        max-pool-prepared-statement-per-connection-size: 20 #\u5F53\u503C\u5927\u4E8E20\u65F6poolPreparedStatements\u4F1A\u81EA\u52A8\u4FEE\u6539\u4E3Atrue
        #\u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true #\u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
        #filters\u901A\u8FC7\u522B\u540D\u7684\u65B9\u5F0F\u914D\u7F6E\u6269\u5C55\u63D2\u4EF6\uFF0C\u5E38\u7528\u7684\u63D2\u4EF6\u6709\uFF1A
        #\u76D1\u63A7\u7EDF\u8BA1\u7528\u7684filter:stat \u65E5\u5FD7\u7528\u7684filter:log4j \u9632\u5FA1sql\u6CE8\u5165\u7684filter:wall
        #filters: stat,wall,log4j
        filters: stat,log4j
      db2:
        #url: jdbc:postgresql://localhost:5432/db_test1
        #driver-class-name: org.postgresql.Driver
        #p6spy SQL\u6027\u80FD\u5206\u6790\u63D2\u4EF6
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:postgresql://localhost:5432/db_test2
        username: postgres
        password: root
        initial-size: 5   # \u8FDE\u63A5\u6C60\u521D\u59CB\u5316\u8FDE\u63A5\u6570\u91CF
        min-idle: 5      # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u6570
        max-active: 20    # \u8FDE\u63A5\u6C60\u6700\u5927\u6D3B\u8DC3\u8FDE\u63A5\u6570
        pool-prepared-statements: true #\u662F\u5426\u7F13\u5B58preparedStatement,mysql5.5+\u5EFA\u8BAE\u5F00\u542F
        max-pool-prepared-statement-per-connection-size: 20 #\u5F53\u503C\u5927\u4E8E20\u65F6poolPreparedStatements\u4F1A\u81EA\u52A8\u4FEE\u6539\u4E3Atrue
        #\u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true #\u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
        #filters\u901A\u8FC7\u522B\u540D\u7684\u65B9\u5F0F\u914D\u7F6E\u6269\u5C55\u63D2\u4EF6\uFF0C\u5E38\u7528\u7684\u63D2\u4EF6\u6709\uFF1A
        #\u76D1\u63A7\u7EDF\u8BA1\u7528\u7684filter:stat \u65E5\u5FD7\u7528\u7684filter:log4j \u9632\u5FA1sql\u6CE8\u5165\u7684filter:wall
        #filters: stat,wall,log4j
        filters: stat,log4j


       # \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D
       # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927


# \u914D\u7F6Esql\u6253\u5370\u65E5\u5FD7\uFF0C\u5F00\u53D1\u73AF\u5883\u9700\u8981\uFF0C\u751F\u4EA7\u73AF\u5883\u4E00\u822C\u4E0D\u9700\u8981
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*.xml  #xml\u6240\u5728\u4F4D\u7F6E  \u4E0D\u8BBE\u7F6E\u9ED8\u8BA4\u662F\u5728mapper\u7C7B\u540C\u7EA7
  type-aliases-package: com.lzy.pojo
  configuration:
    mapUnderscoreToCamelCase: true  # \u5F00\u542F\u9A7C\u5CF0\u5339\u914D  \u9ED8\u8BA4\u4E3Atrue
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u6253\u5370sql\u8BED\u53E5\u548C\u5165\u53C2\u6570\u636E
      #global-config:
      # db-config:
      #logic-delete-value: 1 #\u903B\u8F91\u5220\u9664  \u914D\u5408@TableLogic\u6CE8\u89E3
    #logic-not-delete-value: 0 #\u903B\u8F91\u4E0D\u5220\u9664
    #update-strategy: not_null # \u66F4\u65B0\u65F6\u5B57\u6BB5\u5982\u679C\u4E3Anull\uFF0C\u5C31\u4E0D\u8FDB\u884C\u66F4\u65B0\u8BE5\u5B57\u6BB5\u3002
    #insert-strategy: not_null # \u63D2\u5165\u65F6\u5982\u679C\u5B57\u6BB5\u4E3Anull,\u5C31\u4E0D\u63D2\u5165\u6570\u636E\uFF0C\u5EFA\u8BAE\u6570\u636E\u5E93\u8868\u5B57\u6BB5\u8BBE\u7F6E\u9ED8\u8BA4\u503C

  global-config:
    db-config:
      logic-not-delete-value: 1
      #\u903B\u8F91\u5220\u9664\u914D\u7F6E
      logic-delete-value: 0
      #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
      capital-mode: true



